-- Tạo cơ sở dữ liệu
CREATE DATABASE finly_db;
USE finly_db;

-- Bảng NGUOIDUNG
CREATE TABLE NGUOIDUNG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    HOTEN VARCHAR(100) NOT NULL
);

-- Bảng NGUONTHU
CREATE TABLE NGUONTHU (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NGUOIDUNG_ID INT NOT NULL,
    type ENUM('cash', 'card', 'wallet', 'bank') NOT NULL,
    card_type ENUM('ATM', 'Master', 'Visa') NULL,
    SOTHE VARCHAR(20) NULL,
    SODU DECIMAL(15, 2) DEFAULT 0,
    status TINYINT(1) DEFAULT 1,
    FOREIGN KEY (NGUOIDUNG_ID) REFERENCES NGUOIDUNG(ID) ON DELETE CASCADE
);

-- Bảng DANHMUC
CREATE TABLE DANHMUC (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEN VARCHAR(50) NOT NULL UNIQUE,
    type ENUM('expense', 'income') NOT NULL
);

-- Bảng giaodich
CREATE TABLE GIAODICH (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NGUOIDUNG_ID INT NOT NULL,
    NGUONTHU_ID INT,
    DANHMUC_ID INT NOT NULL,
    type ENUM('income', 'expense') NOT NULL,
    SOTIEN DECIMAL(15, 2) NOT NULL,
    date DATE NULL,
    MOTA TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (NGUOIDUNG_ID) REFERENCES NGUOIDUNG(ID) ON DELETE CASCADE,
    FOREIGN KEY (NGUONTHU_ID) REFERENCES NGUONTHU(ID) ON DELETE SET NULL,
    FOREIGN KEY (DANHMUC_ID) REFERENCES DANHMUC(ID) ON DELETE RESTRICT
);





